from pathlib import Path
import json
import re

import streamlit as st


# ============================================================
# PAGE CONFIG
# ============================================================

st.set_page_config(
    page_title="TrekTales",
    page_icon="🌿",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ============================================================
# COLORS
# ============================================================

RED = "#DA2C38"
GREEN = "#226F54"
LIGHT_GREEN = "#87C38F"
CREAM = "#F5F1E8"
BROWN = "#6B4F3A"
WHITE = "#FFFFFF"
DARK_GREEN = "#163A2A"
BLACK = "#000000"
SOFT_WHITE = "#FAFAF7"
LIGHT_GREY = "#E5E7EB"


# ============================================================
# PROJECT PATHS
# ============================================================

ROOT_DIR = Path(__file__).resolve().parent

SRC_DIR = ROOT_DIR / "src"
ASSETS_DIR = ROOT_DIR / "assets"

KNOWLEDGE_BASE_DIR = ROOT_DIR / "tourism_knowledge_base"
FAISS_DIR = ROOT_DIR / "faiss_db"

FAISS_INDEX_PATH = FAISS_DIR / "index.faiss"
FAISS_METADATA_PATH = FAISS_DIR / "metadata.json"
FAISS_CONFIG_PATH = FAISS_DIR / "config.json"

PAYMENT_QR_PATH = ASSETS_DIR / "jazzcash_qr.jpg"


# ============================================================
# SAFE SECRET READER
# ============================================================

def get_secret(name: str, default=None):
    """
    Safely read a Streamlit secret.

    Priority:
    1. Streamlit secrets
    2. Default value
    """

    try:
        value = st.secrets.get(name)

        if value is not None and str(value).strip():
            return value

    except Exception:
        pass

    return default


# ============================================================
# CONFIGURATION
# ============================================================

GROQ_API_KEY = get_secret("GROQ_API_KEY", "")

GROQ_MODEL = get_secret(
    "GROQ_MODEL",
    "openai/gpt-oss-120b",
)

GROQ_BASE_URL = get_secret(
    "GROQ_BASE_URL",
    "https://api.groq.com/openai/v1",
)

GROQ_VISION_MODEL = get_secret(
    "GROQ_VISION_MODEL",
    "meta-llama/llama-4-scout-17b-16e-instruct",
)

EXPECTED_PAYMENT_RECIPIENT = get_secret(
    "EXPECTED_PAYMENT_RECIPIENT",
    "",
)

# Optional maximum output token setting.
try:
    GROQ_MAX_TOKENS = int(
        get_secret("GROQ_MAX_TOKENS", "3500")
    )
except Exception:
    GROQ_MAX_TOKENS = 3500


# ============================================================
# OPTIONAL CONFIG MODULE
# ============================================================

try:
    from src import config as app_config

    GROQ_API_KEY = getattr(
        app_config,
        "GROQ_API_KEY",
        GROQ_API_KEY,
    )

    GROQ_MODEL = getattr(
        app_config,
        "GROQ_MODEL",
        GROQ_MODEL,
    )

    GROQ_BASE_URL = getattr(
        app_config,
        "GROQ_BASE_URL",
        GROQ_BASE_URL,
    )

    GROQ_VISION_MODEL = getattr(
        app_config,
        "GROQ_VISION_MODEL",
        GROQ_VISION_MODEL,
    )

except Exception:
    app_config = None


# ============================================================
# SESSION STATE
# ============================================================

DEFAULT_SESSION_STATE = {
    "payment_verified": False,
    "trip_result": "",
    "trip_evidence": [],
    "payment_result": None,
    "vision_result": None,
    "last_error": "",
}


for key, value in DEFAULT_SESSION_STATE.items():

    if key not in st.session_state:
        st.session_state[key] = value


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def clean_text(value):
    """
    Remove accidental HTML/code-fence artifacts while preserving
    Markdown content generated by the AI.
    """

    if value is None:
        return ""

    text = str(value)

    # Remove code fences only.
    text = re.sub(
        r"```(?:markdown|md|text)?",
        "",
        text,
        flags=re.IGNORECASE,
    )

    text = text.replace("```", "")

    # Remove common HTML tags.
    text = re.sub(
        r"<\s*/?\s*(p|div|span|br|strong|b|em|i|section|article|ul|ol|li|h1|h2|h3|h4|h5|h6)[^>]*>",
        "",
        text,
        flags=re.IGNORECASE,
    )

    # Remove accidental HTML comments.
    text = re.sub(
        r"<!--.*?-->",
        "",
        text,
        flags=re.DOTALL,
    )

    return text.strip()


def normalize_evidence(evidence):
    """
    Normalize retrieved FAISS evidence into a list of dictionaries.
    """

    if evidence is None:
        return []

    if isinstance(evidence, dict):

        for key in (
            "results",
            "documents",
            "items",
            "matches",
            "evidence",
        ):

            if isinstance(evidence.get(key), list):
                evidence = evidence[key]
                break

        else:
            evidence = [evidence]

    if not isinstance(evidence, (list, tuple)):
        evidence = [evidence]

    normalized = []

    for item in evidence:

        if item is None:
            continue

        if isinstance(item, str):

            text = item.strip()

            if text:
                normalized.append(
                    {
                        "text": text,
                        "source": "Unknown",
                    }
                )

            continue

        if isinstance(item, dict):

            metadata = item.get("metadata")

            if not isinstance(metadata, dict):
                metadata = {}

            text = (
                item.get("text")
                or item.get("content")
                or item.get("chunk")
                or item.get("document")
                or metadata.get("text")
                or metadata.get("content")
                or ""
            )

            source = (
                item.get("source")
                or item.get("filename")
                or item.get("file")
                or metadata.get("source")
                or metadata.get("filename")
                or metadata.get("file")
                or "Unknown"
            )

            page = (
                item.get("page")
                or metadata.get("page")
                or ""
            )

            if text:

                normalized.append(
                    {
                        "text": str(text).strip(),
                        "source": str(source).strip(),
                        "page": str(page).strip(),
                    }
                )

    return normalized


def format_source_name(source):
    """
    Make source names clean for UI display.
    """

    if not source:
        return "Unknown"

    source = str(source)

    source = source.replace("\\", "/")

    source = source.split("/")[-1]

    source = source.replace(".html", "")
    source = source.replace(".htm", "")

    return source.strip()


def source_list(evidence):
    """
    Extract unique source filenames.
    """

    sources = []

    for item in normalize_evidence(evidence):

        source = format_source_name(
            item.get("source", "")
        )

        if source and source != "Unknown":
            sources.append(source)

    return list(dict.fromkeys(sources))


# ============================================================
# CSS
# ============================================================

st.markdown(
    f"""
<style>

html, body, [class*="css"] {{
    font-family: Arial, sans-serif;
}}

.stApp {{
    background:
        linear-gradient(
            135deg,
            #F5F1E8 0%,
            #FAFAF7 45%,
            #EAF4ED 100%
        );
}}

.main {{
    padding-top: 1rem;
}}

.block-container {{
    max-width: 1250px;
    padding-top: 1.5rem;
    padding-bottom: 3rem;
}}

/* Sidebar */

section[data-testid="stSidebar"] {{
    background:
        linear-gradient(
            180deg,
            {DARK_GREEN},
            {GREEN}
        );
}}

section[data-testid="stSidebar"] * {{
    color: white !important;
}}

/* Headers */

h1, h2, h3, h4 {{
    color: {DARK_GREEN} !important;
}}

p, li {{
    color: {BLACK};
}}

/* Buttons */

.stButton > button {{
    border-radius: 12px;
    border: none;
    background:
        linear-gradient(
            135deg,
            {GREEN},
            {LIGHT_GREEN}
        );
    color: white;
    font-weight: 700;
    min-height: 45px;
    padding: 0.65rem 1.2rem;
    transition: 0.2s ease;
}}

.stButton > button:hover {{
    transform: translateY(-1px);
    box-shadow: 0 6px 18px rgba(0,0,0,0.12);
}}

/* Inputs */

.stTextInput input,
.stNumberInput input,
.stTextArea textarea {{
    border-radius: 10px !important;
    border: 1px solid #CBD5D1 !important;
    background: white !important;
    color: #111827 !important;
}}

div[data-baseweb="select"] > div {{
    background: white !important;
    color: #111827 !important;
    border-radius: 10px !important;
}}

/* Hero */

.hero {{
    background:
        linear-gradient(
            135deg,
            rgba(34,111,84,0.96),
            rgba(22,58,42,0.98)
        );
    padding: 2.5rem;
    border-radius: 24px;
    color: white;
    margin-bottom: 1.5rem;
    box-shadow: 0 14px 40px rgba(22,58,42,0.18);
}}

.hero h1 {{
    color: white !important;
    font-size: 3rem;
    margin-bottom: 0.5rem;
}}

.hero p {{
    color: #F3F8F4 !important;
    font-size: 1.05rem;
}}

.brand {{
    font-size: 1.4rem;
    font-weight: 800;
    color: white;
    letter-spacing: 0.5px;
}}

.feature-card {{
    background: rgba(255,255,255,0.88);
    border: 1px solid rgba(34,111,84,0.12);
    border-radius: 18px;
    padding: 1.2rem;
    min-height: 145px;
    box-shadow: 0 8px 24px rgba(0,0,0,0.06);
}}

.feature-card h3 {{
    margin-top: 0;
    color: {DARK_GREEN} !important;
}}

.feature-card p {{
    color: #374151 !important;
}}

.status-card {{
    background: white;
    border-radius: 16px;
    border: 1px solid #E5E7EB;
    padding: 1rem 1.2rem;
    margin: 0.5rem 0;
}}

.itinerary-card {{
    background: white;
    border-radius: 18px;
    padding: 1.8rem;
    border: 1px solid #E5E7EB;
    box-shadow: 0 8px 30px rgba(0,0,0,0.06);
}}

.source-card {{
    background: #F8FAF9;
    border-left: 4px solid {GREEN};
    border-radius: 10px;
    padding: 0.8rem 1rem;
    margin-bottom: 0.5rem;
}}

.payment-card {{
    background: white;
    border-radius: 18px;
    border: 2px solid {LIGHT_GREEN};
    padding: 1.5rem;
}}

.disclaimer {{
    background: #FFF7ED;
    border-left: 5px solid #F59E0B;
    border-radius: 10px;
    padding: 1rem;
    margin-top: 1.5rem;
}}

.footer {{
    text-align: center;
    color: #6B7280;
    padding: 2rem 0 1rem 0;
}}

</style>
""",
    unsafe_allow_html=True,
)


# ============================================================
# IMPORT APPLICATION MODULES
# ============================================================

retriever_import_error = None
crew_import_error = None
vision_import_error = None
payment_import_error = None


try:

    from src.retriever import HybridRetriever

except Exception as exc:

    HybridRetriever = None
    retriever_import_error = exc


try:

    from src.crew import TrekTalesCrew

except Exception as exc:

    TrekTalesCrew = None
    crew_import_error = exc


try:

    from src.vision import analyze_payment_screenshot

except Exception as exc:

    analyze_payment_screenshot = None
    vision_import_error = exc


try:

    from src.payment import verify_payment

except Exception as exc:

    verify_payment = None
    payment_import_error = exc


# ============================================================
# HEADER
# ============================================================

st.markdown(
    """
<div style="
    display:flex;
    justify-content:space-between;
    align-items:center;
    padding:0.5rem 0 1rem 0;
">
    <div class="brand">
        🌿 TrekTales
    </div>
    <div style="
        color:#226F54;
        font-weight:700;
    ">
        AI-Powered Pakistan Travel Planner
    </div>
</div>
""",
    unsafe_allow_html=True,
)


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.markdown(
        "## 🌿 TrekTales"
    )

    st.markdown(
        "### Travel Planning System"
    )

    st.divider()

    st.markdown(
        "### 🔐 Access Model"
    )

    if st.session_state.payment_verified:

        st.success(
            "Premium access unlocked"
        )

    else:

        st.info(
            "Free access: Day 1"
        )

    st.markdown(
        "### 🤖 AI Agents"
    )

    agents = [
        "🎯 Master Orchestrator",
        "📚 Knowledge Agent",
        "🗺️ Planner Agent",
        "💰 Budget Agent",
        "🛡️ Safety Agent",
        "📝 Summarizer Agent",
        "💳 Payment Agent",
        "👁️ Vision Agent",
    ]

    for agent in agents:
        st.markdown(
            f"- {agent}"
        )

    st.divider()

    st.markdown(
        "### ⚙️ Groq Model"
    )

    st.caption(
        GROQ_MODEL
    )

    st.divider()

    st.caption(
        "TrekTales uses retrieved tourism knowledge "
        "and Groq-powered generation."
    )


# ============================================================
# HERO
# ============================================================

st.markdown(
    f"""
<div class="hero">

<h1>🌿 TrekTales</h1>

<p>
Plan personalized trips across Pakistan using
retrieved tourism information, intelligent itinerary
generation, budget-aware planning, and AI assistance.
</p>

<p>
<strong>Grounded planning.</strong>
The itinerary generator is instructed not to invent
tourism facts that are missing from the knowledge base.
</p>

</div>
""",
    unsafe_allow_html=True,
)


# ============================================================
# FEATURE CARDS
# ============================================================

col1, col2, col3 = st.columns(3)

with col1:

    st.markdown(
        """
<div class="feature-card">

<h3>📚 Knowledge Grounding</h3>

<p>
Relevant tourism information is retrieved from
the TrekTales FAISS knowledge base before
the itinerary is generated.
</p>

</div>
""",
        unsafe_allow_html=True,
    )


with col2:

    st.markdown(
        """
<div class="feature-card">

<h3>🗺️ Personalized Planning</h3>

<p>
Trip duration, travelers, budget, starting point,
travel style, interests, and language are used
to personalize the itinerary.
</p>

</div>
""",
        unsafe_allow_html=True,
    )


with col3:

    st.markdown(
        """
<div class="feature-card">

<h3>🛡️ Grounded Answers</h3>

<p>
Unsupported prices, distances, timings,
restaurants, attractions, and other facts
are not supposed to be fabricated.
</p>

</div>
""",
        unsafe_allow_html=True,
    )


st.write("")


# ============================================================
# TRIP PLANNER
# ============================================================

st.markdown(
    "## 🧭 Plan Your Journey"
)

st.markdown(
    "Tell TrekTales what kind of trip you want to create."
)


col1, col2 = st.columns(2)

with col1:

    starting_location = st.text_input(
        "📍 Starting Location",
        value="Sibbi",
        placeholder="Example: Lahore, Islamabad, Sibbi",
    )


with col2:

    destination = st.text_input(
        "🏞️ Destination",
        value="Rawalpindi",
        placeholder="Example: Rawalpindi, Hunza, Lahore",
    )


col1, col2, col3 = st.columns(3)

with col1:

    duration = st.selectbox(
        "📅 Trip Duration",
        options=[1, 2, 3],
        format_func=lambda x: (
            f"{x} Day"
            if x == 1
            else f"{x} Days"
        ),
    )


with col2:

    travelers = st.number_input(
        "👥 Travelers",
        min_value=1,
        max_value=20,
        value=2,
        step=1,
    )


with col3:

    budget = st.selectbox(
        "💰 Budget",
        options=[
            "Budget",
            "Moderate",
            "Comfort",
            "Premium",
        ],
    )


col1, col2 = st.columns(2)

with col1:

    travel_style = st.selectbox(
        "🥾 Travel Style",
        options=[
            "Relaxed",
            "Adventure",
            "Active & Outdoor",
            "Family",
            "Cultural",
            "Luxury",
            "Backpacking",
        ],
    )


with col2:

    language = st.selectbox(
        "🌐 Response Language",
        options=[
            "English",
            "Urdu",
            "Roman Urdu",
        ],
    )


interests = st.multiselect(
    "❤️ Interests",
    options=[
        "Nature",
        "Photography",
        "Local Culture",
        "History",
        "Food",
        "Adventure",
        "Shopping",
        "Mountains",
        "Wildlife",
        "Family Activities",
        "Architecture",
        "Relaxation",
    ],
    default=[
        "Nature",
        "Photography",
        "Local Culture",
    ],
)


# ============================================================
# SYSTEM STATUS
# ============================================================

st.markdown(
    "## ⚙️ System Status"
)

status_col1, status_col2, status_col3 = st.columns(3)

with status_col1:

    if FAISS_INDEX_PATH.exists():

        st.success(
            "📚 FAISS database found"
        )

    else:

        st.error(
            "❌ FAISS index not found"
        )


with status_col2:

    if GROQ_API_KEY:

        st.success(
            "🤖 Groq API configured"
        )

    else:

        st.error(
            "❌ Groq API key missing"
        )


with status_col3:

    if TrekTalesCrew is not None:

        st.success(
            "🧠 AI crew available"
        )

    else:

        st.error(
            "❌ AI crew unavailable"
        )


# ============================================================
# GENERATION BUTTON
# ============================================================

st.write("")

generate_clicked = st.button(
    "🌿 Generate My TrekTales Itinerary",
    use_container_width=True,
)


# ============================================================
# GENERATE ITINERARY
# ============================================================

if generate_clicked:

    st.session_state.last_error = ""

    st.session_state.trip_result = ""

    st.session_state.trip_evidence = []

    # --------------------------------------------------------
    # Validate inputs
    # --------------------------------------------------------

    if not starting_location.strip():

        st.error(
            "Please enter your starting location."
        )

        st.stop()


    if not destination.strip():

        st.error(
            "Please enter a destination."
        )

        st.stop()


    if not interests:

        st.warning(
            "Please select at least one interest."
        )

        st.stop()


    # --------------------------------------------------------
    # Check API
    # --------------------------------------------------------

    if not GROQ_API_KEY:

        st.error(
            "GROQ_API_KEY is not configured. "
            "Add it to Streamlit Secrets."
        )

        st.stop()


    # --------------------------------------------------------
    # Check retriever
    # --------------------------------------------------------

    if HybridRetriever is None:

        st.error(
            "The tourism retriever could not be imported."
        )

        if retriever_import_error:

            st.code(
                str(retriever_import_error)
            )

        st.stop()


    # --------------------------------------------------------
    # Check FAISS
    # --------------------------------------------------------

    if not FAISS_INDEX_PATH.exists():

        st.error(
            "FAISS database not found."
        )

        st.markdown(
            f"""
Expected file:

`{FAISS_INDEX_PATH}`

Please make sure your GitHub repository contains:

`faiss_db/index.faiss`

and:

`faiss_db/metadata.json`
"""
        )

        st.stop()


    # --------------------------------------------------------
    # Free / Premium day control
    # --------------------------------------------------------

    requested_days = int(duration)

    if st.session_state.payment_verified:

        generation_days = requested_days

    else:

        generation_days = 1

    # --------------------------------------------------------
    # Retrieval query
    # --------------------------------------------------------

    retrieval_query = f"""
Destination: {destination}

Starting location: {starting_location}

Requested duration: {requested_days} days

Travelers: {travelers}

Budget: {budget}

Travel style: {travel_style}

Interests:
{", ".join(interests)}

Find tourism knowledge relevant to:
- destination
- attractions
- activities
- transportation
- prices
- entry fees
- food
- cultural experiences
- photography
- travel planning
- safety information
- budget information
"""

    # --------------------------------------------------------
    # Retrieve knowledge
    # --------------------------------------------------------

    try:

        with st.spinner(
            "📚 Searching the TrekTales tourism knowledge base..."
        ):

            retriever = None

            # Preferred constructor.
            try:

                retriever = HybridRetriever(
                    index_path=FAISS_INDEX_PATH,
                    metadata_path=FAISS_METADATA_PATH,
                    config_path=FAISS_CONFIG_PATH,
                )

            except TypeError:

                # Compatibility with alternate constructor.
                try:

                    retriever = HybridRetriever(
                        str(FAISS_INDEX_PATH),
                        str(FAISS_METADATA_PATH),
                        str(FAISS_CONFIG_PATH),
                    )

                except TypeError:

                    retriever = HybridRetriever(
                        FAISS_INDEX_PATH,
                        FAISS_METADATA_PATH,
                    )


            if hasattr(retriever, "search"):

                try:

                    evidence = retriever.search(
                        retrieval_query,
                        top_k=8,
                    )

                except TypeError:

                    evidence = retriever.search(
                        retrieval_query
                    )

            elif hasattr(retriever, "retrieve"):

                try:

                    evidence = retriever.retrieve(
                        retrieval_query,
                        top_k=8,
                    )

                except TypeError:

                    evidence = retriever.retrieve(
                        retrieval_query
                    )

            else:

                raise RuntimeError(
                    "HybridRetriever does not provide "
                    "a search() or retrieve() method."
                )


        evidence = normalize_evidence(
            evidence
        )

        st.session_state.trip_evidence = evidence

        if not evidence:

            st.warning(
                "No relevant tourism information was "
                "retrieved from the knowledge base."
            )

            st.stop()


        st.success(
            f"Retrieved {len(evidence)} knowledge items."
        )


    except Exception as exc:

        st.session_state.last_error = str(exc)

        st.error(
            "❌ Tourism knowledge retrieval failed."
        )

        st.exception(exc)

        st.stop()


    # --------------------------------------------------------
    # Premium lock message
    # --------------------------------------------------------

    if requested_days > generation_days:

        st.warning(
            f"Days 2–{requested_days} are locked. "
            "Complete the Rs. 199 premium verification "
            "to unlock the requested trip duration."
        )


    # --------------------------------------------------------
    # Generate
    # --------------------------------------------------------

    if TrekTalesCrew is None:

        st.error(
            "TrekTales AI crew could not be imported."
        )

        if crew_import_error:

            st.code(
                str(crew_import_error)
            )

        st.stop()


    try:

        with st.spinner(
            "🤖 Activating TrekTales AI planning system..."
        ):

            crew = TrekTalesCrew()

            result = crew.run(
                destination=destination,
                starting_location=starting_location,
                duration=generation_days,
                requested_duration=requested_days,
                travelers=int(travelers),
                budget=budget,
                travel_style=travel_style,
                interests=interests,
                language=language,
                evidence=evidence,
            )


        result = clean_text(result)

        if not result:

            raise RuntimeError(
                "The AI returned an empty itinerary."
            )


        st.session_state.trip_result = result

        st.success(
            "🌿 Your itinerary has been generated."
        )


    except Exception as exc:

        st.session_state.last_error = str(exc)

        st.error(
            "❌ Trip generation failed."
        )

        st.exception(exc)


# ============================================================
# ITINERARY RESULT
# ============================================================

if st.session_state.trip_result:

    st.write("")

    st.markdown(
        "## 🌿 Your TrekTales Itinerary"
    )

    st.markdown(
        '<div class="itinerary-card">',
        unsafe_allow_html=True,
    )

    answer = clean_text(
        st.session_state.trip_result
    )

    # IMPORTANT:
    # Do not add another artificial itinerary title here.
    # The AI-generated Markdown already contains the
    # personalized itinerary heading.

    st.markdown(
        answer,
        unsafe_allow_html=False,
    )

    st.markdown(
        "</div>",
        unsafe_allow_html=True,
    )


# ============================================================
# KNOWLEDGE SOURCES
# ============================================================

if st.session_state.trip_evidence:

    st.write("")

    with st.expander(
        "📚 Retrieved Knowledge Sources",
        expanded=False,
    ):

        sources = source_list(
            st.session_state.trip_evidence
        )

        if sources:

            for source in sources:

                st.markdown(
                    f"""
<div class="source-card">
📄 <strong>{source}</strong>
</div>
""",
                    unsafe_allow_html=True,
                )

        else:

            st.info(
                "Source filenames were not available."
            )


# ============================================================
# PREMIUM PAYMENT
# ============================================================

st.write("")

st.markdown(
    "## 💳 Premium Access"
)

st.markdown(
    """
<div class="payment-card">

<h3>🔓 Unlock Extended Itineraries</h3>

<p>
Free access generates Day 1.
Premium verification unlocks the requested
multi-day itinerary.
</p>

<p>
<strong>Premium verification price: Rs. 199</strong>
</p>

</div>
""",
    unsafe_allow_html=True,
)


payment_col1, payment_col2 = st.columns(2)

with payment_col1:

    if PAYMENT_QR_PATH.exists():

        st.image(
            str(PAYMENT_QR_PATH),
            caption="JazzCash Payment QR",
            width=280,
        )

    else:

        st.warning(
            "Payment QR image was not found."
        )

        st.caption(
            f"Expected: {PAYMENT_QR_PATH}"
        )


with payment_col2:

    st.markdown(
        "### 📤 Upload Payment Screenshot"
    )

    payment_file = st.file_uploader(
        "Upload your payment screenshot",
        type=[
            "png",
            "jpg",
            "jpeg",
            "webp",
        ],
        key="payment_upload",
    )


    verify_button = st.button(
        "🔍 Verify Payment",
        use_container_width=True,
    )


    if verify_button:

        if payment_file is None:

            st.warning(
                "Please upload a payment screenshot first."
            )

        elif analyze_payment_screenshot is None:

            st.error(
                "Vision verification module could not be imported."
            )

            if vision_import_error:

                st.code(
                    str(vision_import_error)
                )

        elif verify_payment is None:

            st.error(
                "Payment verification module could not be imported."
            )

            if payment_import_error:

                st.code(
                    str(payment_import_error)
                )

        else:

            try:

                with st.spinner(
                    "👁️ Analyzing payment screenshot..."
                ):

                    image_bytes = payment_file.getvalue()

                    try:

                        vision_result = analyze_payment_screenshot(
                            image_bytes=image_bytes,
                            api_key=GROQ_API_KEY,
                            model=GROQ_VISION_MODEL,
                            base_url=GROQ_BASE_URL,
                        )

                    except TypeError:

                        try:

                            vision_result = analyze_payment_screenshot(
                                image_bytes,
                                GROQ_API_KEY,
                                GROQ_VISION_MODEL,
                                GROQ_BASE_URL,
                            )

                        except TypeError:

                            vision_result = analyze_payment_screenshot(
                                image_bytes
                            )


                st.session_state.vision_result = (
                    vision_result
                )

                st.success(
                    "Vision analysis completed."
                )


                # ------------------------------------------------
                # Verify payment result
                # ------------------------------------------------

                try:

                    try:

                        payment_result = verify_payment(
                            vision_result=vision_result,
                            expected_recipient=EXPECTED_PAYMENT_RECIPIENT,
                        )

                    except TypeError:

                        try:

                            payment_result = verify_payment(
                                vision_result,
                                EXPECTED_PAYMENT_RECIPIENT,
                            )

                        except TypeError:

                            payment_result = verify_payment(
                                vision_result
                            )


                except Exception as payment_exc:

                    payment_result = {
                        "verified": False,
                        "message": str(payment_exc),
                    }


                st.session_state.payment_result = (
                    payment_result
                )


                # ------------------------------------------------
                # Normalize verification result
                # ------------------------------------------------

                verified = False

                if isinstance(
                    payment_result,
                    bool,
                ):

                    verified = payment_result

                elif isinstance(
                    payment_result,
                    dict,
                ):

                    verified = bool(
                        payment_result.get("verified")
                        or payment_result.get("success")
                        or payment_result.get("is_valid")
                    )

                elif isinstance(
                    payment_result,
                    str,
                ):

                    lower_result = (
                        payment_result.lower()
                    )

                    verified = (
                        "verified" in lower_result
                        and "not verified" not in lower_result
                        and "unverified" not in lower_result
                    )


                if verified:

                    st.session_state.payment_verified = True

                    st.success(
                        "✅ Payment verified. "
                        "Premium access is now unlocked."
                    )

                    if isinstance(
                        payment_result,
                        dict,
                    ):

                        message = (
                            payment_result.get("message")
                            or payment_result.get("reason")
                            or ""
                        )

                        if message:
                            st.info(
                                str(message)
                            )

                else:

                    st.session_state.payment_verified = False

                    st.error(
                        "❌ Payment could not be verified."
                    )

                    if isinstance(
                        payment_result,
                        dict,
                    ):

                        message = (
                            payment_result.get("message")
                            or payment_result.get("reason")
                            or ""
                        )

                        if message:
                            st.info(
                                str(message)
                            )

            except Exception as exc:

                st.error(
                    "❌ Payment verification failed."
                )

                st.exception(exc)


# ============================================================
# PAYMENT RESULT DETAILS
# ============================================================

if st.session_state.vision_result is not None:

    with st.expander(
        "👁️ Payment Analysis Details",
        expanded=False,
    ):

        vision_data = (
            st.session_state.vision_result
        )

        if isinstance(
            vision_data,
            (dict, list),
        ):

            st.json(
                vision_data
            )

        else:

            st.write(
                vision_data
            )


# ============================================================
# DISCLAIMER
# ============================================================

st.markdown(
    """
<div class="disclaimer">

<strong>⚠️ Important Information</strong>

<p>
TrekTales is an AI-powered travel planning tool.
Its itinerary recommendations are generated from
the available tourism knowledge base and user inputs.
</p>

<p>
Tourism prices, transportation availability,
opening hours, entry fees, weather, road conditions,
and other real-world information can change.
Please verify important details before traveling.
</p>

<p>
TrekTales should not be treated as a guarantee of
current availability, pricing, safety conditions,
or transportation schedules.
</p>

</div>
""",
    unsafe_allow_html=True,
)


# ============================================================
# FOOTER
# ============================================================

st.markdown(
    """
<div class="footer">

🌿 <strong>TrekTales</strong>

<br>

AI-powered personalized travel planning for Pakistan.

<br><br>

© 2026 TrekTales. All Rights Reserved.

</div>
""",
    unsafe_allow_html=True,
)
